# Generated by Django 3.1.4 on 2021-08-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0008_auto_20210824_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
